version: "3.8"

services:
  # 1. The Brain (Java Manager)
  manager:
    build:
      context: . # <-- CHANGED TO ROOT
      dockerfile: manager/Dockerfile # <-- ADDED
    ports:
      - "8080:8080"
    environment:
      - WORKER_SERVICE_NAME=worker
    depends_on:
      - worker
    networks:
      - grid-net

  # 2. The Muscle (C++ Worker)
  worker:
    build:
      context: . # <-- CHANGED TO ROOT
      dockerfile: worker/Dockerfile # <-- ADDED
    ports:
      - "50051:50051"
    volumes:
      - ./models:/models
    networks:
      - grid-net

  # 3. The Dashboard (React/Vite)
  dashboard:
    build:
      context: ./dashboard # <-- Stays the same (doesn't need protos)
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - grid-net

networks:
  grid-net:
    driver: bridge
