apiVersion: v1
kind: Service
metadata:
  name: gridmind-api
spec:
  selector:
    app: gridmind-node
  type: LoadBalancer  # Or NodePort if running locally (e.g., Minikube)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridmind-cluster
spec:
  replicas: 3  # We will run 3 "nodes" to simulate a grid
  selector:
    matchLabels:
      app: gridmind-node
  template:
    metadata:
      labels:
        app: gridmind-node
    spec:
      containers:
        # -------------------------------------------------
        # Container 1: The Manager (Java Brain)
        # -------------------------------------------------
        - name: manager-node
          image: gridmind-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # REST API
            - containerPort: 9999 # UDP Gossip
          env:
            - name: WORKER_TARGET
              value: "localhost:50051" # Talking to the container next door

        # -------------------------------------------------
        # Container 2: The Worker (C++ Muscle)
        # -------------------------------------------------
        - name: worker-sidecar
          image: gridmind-worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
